### PR TITLE
Update jupyter-server

### PR DESCRIPTION
**Pull request by hbcarlos**
Updates jupyter-server dependency to use jupyter-server>=2,<3

### CODE REVIEW

**Comment by hbcarlos** [comment]
@Zsailer, Why are we pinning jupyer-server=1.8?

**Comment by jtpio** [comment]
> @Zsailer, Why are we pinning jupyer-server=1.8?

Looks like it's `jupyter_server~=1.8` using the `~=` specifier, not an exact pin, which means it accepts `jupyter_server>=1.8,<2`?

**Comment by hbcarlos** [comment]
ooh, that's right. Thanks, @jtpio!

**Comment by Zsailer** [comment]
Thanks, @hbcarlos. See #12 

I don't think we want to *require* > 2.0. We just need to raise the ceiling on allowed versions of Jupyter Server. JupyterLab 4.0 can require >2, but I don't think we should enforce this on all consumers of notebook_shim.

**Pull request closed without merging**
