### PR TITLE
Add show_banner to ignored_traits

### PR DESCRIPTION
**Pull request by echarles**
Contributes to https://github.com/jupyter/nbclassic/issues/242

Once this is merged and released, https://github.com/jupyter/nbclassic/pull/243 needs to be upated.

### CODE REVIEW

**Comment by echarles** [comment]
@Zsailer @jtpio any chance to get this reviewed? We will need a release after, any volunteer for that? (I don't know if I have the rights for a release).

**Comment by jtpio** [comment]
Looks like the CI failure might not be relevant, but would still be good to address before a new release?

**Comment by echarles** [comment]
Thx @jtpio CI is green now.

**Review by Zsailer — APPROVED** [review]

**Comment by echarles** [comment]
Thx @Zsailer Is it possible to get a release with this PR?

**Comment by Zsailer** [comment]
Yeah, happy to cut the release.

You should have permissions too—it looks like all notebook team members are listed as admin on this repo.

**Comment by echarles** [comment]
I am not liste on pypi for notebook_shim, I let you cut the release this time. Thx.

**Comment by Zsailer** [comment]
Ah, I see. Just added you as a maintainer on the PyPi package.

Released: https://github.com/jupyter/notebook_shim/releases/tag/v0.2.3

**Pull request merged**
